In [2]:
import numpy as np

In [3]:
print("hello")

hello


In [4]:
arr=np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [7]:
arr = [[30,40,50],[60,70,80]]
arr = np.array(arr)
print(arr)
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(arr.dtype)

[[30 40 50]
 [60 70 80]]
(2, 3)
2
6
int64


In [9]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr+arr2)

[[31 42 53]
 [64 75 86]]


In [10]:
arr1 = np.array([2,3,1])
arr2 = np.array([2])

print(np.power(arr1,arr2))


[4 9 1]


In [12]:
np.concatenate((arr1, arr2), axis=0)
print(arr1.max())

3


In [28]:
arr = [[30,40,50],[60,70,80]]
arr = np.array(arr)
arr2=np.array([[1,2,3],[4,5,6]])
np.hstack((arr, arr2))

arr = np.append(arr, [[90,100,110]], axis=0)
print(arr)

print(np.sort(arr))
print(arr[arr>35])



[[ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]]
[[ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]]
[ 40  50  60  70  80  90 100 110]


In [29]:
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.cumsum(arr))

630
30
110
[ 30  70 120 180 250 330 420 520 630]


In [31]:
tobacco_consumption = np.array([2.5, 3.0, 2.8, 3.2, 2.9])
deaths= np.array([1000, 1200, 1100, 1300, 1150])
print(np.corrcoef(tobacco_consumption, deaths))


[[1.         0.99344869]
 [0.99344869 1.        ]]


In [34]:
import pandas as pd

data={"Name":["Alice","Bob","Charlie","David"],
      "Age":[25,30,35,40],
      "Salary":[50000,60000,70000,80000]}

df=pd.DataFrame(data)
print(df)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000


In [35]:
pip install openpyxl



   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [ope

In [37]:
df = pd.read_csv(r"C:\Users\HP-PC\Desktop\pyhton\Zomato-data-.csv")


In [38]:
print(df.head())

                    name online_order book_table   rate  votes  \
0                  Jalsa          Yes        Yes  4.1/5    775   
1         Spice Elephant          Yes         No  4.1/5    787   
2        San Churro Cafe          Yes         No  3.8/5    918   
3  Addhuri Udupi Bhojana           No         No  3.7/5     88   
4          Grand Village           No         No  3.8/5    166   

   approx_cost(for two people) listed_in(type)  
0                          800          Buffet  
1                          800          Buffet  
2                          800          Buffet  
3                          300          Buffet  
4                          600          Buffet  


In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64 
 5   approx_cost(for two people)  148 non-null    int64 
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB


In [40]:
df.describe()

,votes,approx_cost(for two people)
count,148.000000,148.000000
mean,264.810811,418.243243
std,653.676951,223.085098
min,0.000000,100.000000
25%,6.750000,200.000000
50%,43.500000,400.000000
75%,221.750000,600.000000
max,4884.000000,950.000000


In [48]:
print(df['votes'].isnull())


0      False
1      False
2      False
3      False
4      False
       ...  
143    False
144    False
145    False
146    False
147    False
Name: votes, Length: 148, dtype: bool


In [53]:
print(df.loc[df['votes'] > 4.5/5].count())

name                           115
online_order                   115
book_table                     115
rate                           115
votes                          115
approx_cost(for two people)    115
listed_in(type)                115
dtype: int64


In [55]:
df["name"]=df["name"].str.upper()

In [56]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,JALSA,Yes,Yes,4.1/5,775,800,Buffet
1,SPICE ELEPHANT,Yes,No,4.1/5,787,800,Buffet
2,SAN CHURRO CAFE,Yes,No,3.8/5,918,800,Buffet
3,ADDHURI UDUPI BHOJANA,No,No,3.7/5,88,300,Buffet
4,GRAND VILLAGE,No,No,3.8/5,166,600,Buffet


In [59]:
gp = df.groupby(["online_order","book_table"]).agg({"votes":"mean","approx_cost(for two people)":"mean"})


In [60]:
print(gp)

                              votes  approx_cost(for two people)
online_order book_table                                         
No           No           66.988764                   353.370787
             Yes         808.000000                   850.000000
Yes          No          504.000000                   488.235294
             Yes         959.714286                   671.428571


In [62]:
print(pd.merge(df,df,how="inner",on="name").head())

                    name online_order_x book_table_x rate_x  votes_x  \
0                  JALSA            Yes          Yes  4.1/5      775   
1         SPICE ELEPHANT            Yes           No  4.1/5      787   
2        SAN CHURRO CAFE            Yes           No  3.8/5      918   
3        SAN CHURRO CAFE            Yes           No  3.8/5      918   
4  ADDHURI UDUPI BHOJANA             No           No  3.7/5       88   

   approx_cost(for two people)_x listed_in(type)_x online_order_y  \
0                            800            Buffet            Yes   
1                            800            Buffet            Yes   
2                            800            Buffet            Yes   
3                            800            Buffet            Yes   
4                            300            Buffet             No   

  book_table_y rate_y  votes_y  approx_cost(for two people)_y  \
0          Yes  4.1/5      775                            800   
1           No  4.1/5 